### ISSUE TITLE
Need to download datasets ?

### ISSUE THREAD

**Issue by cbouyssi** [KaiyangZhou/deep-person-reid#111]
Hello,
Have a simple question on how to use the pretrained versions on a given dataset or my own one.
I got the weights "se_resnet50_fc512_market_xent.pth.tar"
And run : 

python train_imgreid_xent.py -t market1501
-s market1501
 --height 256 
--width 128
--test-batch-size 100 
--evaluate 
-a se_resnet50_fc512
--load-weights se_resnet50_fc512_market_xent\se_resnet50_fc512_market_xent.pth.tar --save-dir log\eval-resnet50 
--gpu-devices 0 

But get the following error, as if the dataset was not found.

Traceback (most recent call last):
  File "train_imgreid_xent.py", line 257, in <module>
    main()
  File "train_imgreid_xent.py", line 53, in main
    dm = ImageDataManager(use_gpu, **image_dataset_kwargs(args))
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\data_manager.py", line 68, in __init__
    cuhk03_classic_split=cuhk03_classic_split, market1501_500k=market1501_500k
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\datasets\__init__.py", line 47, in init_imgreid_dataset
    return __imgreid_factory[name](**kwargs)
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\datasets\market1501.py", line 45, in __init__
    self._check_before_run()
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\datasets\market1501.py", line 68, in _check_before_run
    raise RuntimeError('"{}" is not available'.format(self.dataset_dir))
RuntimeError: "data\market1501" is not available

Should I get it manually, and put it in the folder "data\market1501" ?

Now what if I want to try it on a dataset of mine ?

Looking forward to your answer. Thanks

**Comment by KaiyangZhou** [comment]
> RuntimeError: "data\market1501" is not available
I guess the dataset is not stored in `deep-person-reid/data`. You need to specify the root to the data folder, e.g.  add this argument `--root path/to/data`.

> Now what if I want to try it on a dataset of mine ?
Write a new dataset script. You can follow `market1501.py`.

**Comment by cbouyssi** [comment]
Alright, do you have to download the model at any moment ?
I create the path to the data and now I get this error : 

=> Initializing TEST (target) datasets
=> Market1501 loaded
Image Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |     0 |        0 |         0
  query    |     0 |        0 |         0
  gallery  |     0 |        0 |         0
  ----------------------------------------


  **************** Summary ****************
  train names      : ['market1501']
  # train datasets : 1
  # train ids      : 0
  # train images   : 0
  # train cameras  : 0
  test names       : ['market1501']
  *****************************************


Initializing model: se_resnet50_fc512
Traceback (most recent call last):
  File "train_imgreid_xent.py", line 257, in <module>
    main()
  File "train_imgreid_xent.py", line 57, in main
    model = models.init_model(name=args.arch, num_classes=dm.num_train_pids, loss={'xent'}, use_gpu=use_gpu)
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\models\__init__.py", line 63, in init_model
    return __model_factory[name](*args, **kwargs)
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\models\senet.py", line 487, in se_resnet50_fc512
    **kwargs
  File "C:\Users\César Bouyssi\Desktop\FitnessPlus\re_Identification\deep-person-reid\torchreid\models\senet.py", line 338, in __init__
    self.classifier = nn.Linear(self.feature_dim, num_classes)
  File "C:\Users\César Bouyssi\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\linear.py", line 46, in __init__
    self.reset_parameters()
  File "C:\Users\César Bouyssi\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

Which is kinda weird, it seems like no data is given as an input.

**Comment by KaiyangZhou** [comment]
did you follow the instruction to prepare the dataset?

**Comment by cbouyssi** [comment]
Finally found the problem, it was related to a previews issue (needed to change a few things in "serialization.py")
Thank you for your help !!

**Comment by KaiyangZhou** [comment]
good to hear that. please provide a link to the related issue in this thread so others can benefit from it.

**Comment by cbouyssi** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues/43
