### ISSUE TITLE
Combine multiple datasets

### ISSUE THREAD

**Issue by bagxi** [KaiyangZhou/deep-person-reid#132]
Code from [example](https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#combine-multiple-datasets) for multiple datasets
```
...
datamanager = torchreid.data.ImageDataManager(
    root='reid-data',
    sources=['market1501', 'dukemtmcreid'],
    height=256,
    width=128,
    batch_size=32
)
...
```

Traceback
```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    train()
  File "main.py", line 74, in train
    test_only=False,
  File "/usr/local/lib/python3.6/dist-packages/torchreid/engine/engine.py", line 100, in run
    self.train(epoch, trainloader, print_freq=print_freq)
  File "/usr/local/lib/python3.6/dist-packages/torchreid/engine/image/softmax.py", line 98, in train
    for batch_idx, data in enumerate(trainloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
NotImplementedError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torchreid/data/datasets/dataset.py", line 64, in __getitem__
    raise NotImplementedError
NotImplementedError
```

**Comment by KaiyangZhou** [comment]
are you using the latest `0.7.0`?

**Comment by bagxi** [comment]
yup
commit `8e5265099d88e2ef5589532f4327edc0f9112307`

**Comment by KaiyangZhou** [comment]
it's a bit weird, all the image datasets have inherited `ImageDataset` where `__getitem__` has been implemented.

what do you get with just the following code
```
import torchreid

datamanager = torchreid.data.ImageDataManager(
    root='path/to/reid-data',
    sources=['market1501', 'dukemtmcreid']
)
```

**Comment by bagxi** [comment]
The same error.
But for single dataset (e.g. sources=['market1501']) all is fine. And for each separately, too.

**Comment by KaiyangZhou** [comment]
Indeed, that is a very careless bug. Now fixed at https://github.com/KaiyangZhou/deep-person-reid/commit/235348f67248a9d27d5c9bcafcabcfe5cbf61cb3.

Try the latest commit and let me know if it works.

**Comment by bagxi** [comment]
Now everything is fine.
Thank you very much!

**Comment by KaiyangZhou** [comment]
A bug has been fixed for `combineall`. Please use the latest commit (v0.7.4).
