### ISSUE TITLE
Is combined softmax_triple loss available?

### ISSUE THREAD

**Issue by WannaSeaU** [KaiyangZhou/deep-person-reid#155]

**Comment by W-Ted** [comment]
Actually, '--loss triplet --train-sampler RandomIdentitySampler' means combined softmax_triple loss.

**Comment by WannaSeaU** [comment]
@W-Ted Think you for your reply!

**Comment by WannaSeaU** [comment]
Hello, I'm trying to train a video-based reid model with softmax-triplet combined loss, and I choose the pcb_p6 as the backbone model. 

My configuration is as follows:
```shell
python main.py --app video\
               -s    dukemtmcvidreid\
               -t    dukemtmcvidreid\
               --save-dir log/pcb-DukeMTMC-VideoReID-combined\
               --root ../../dataset/DukeMTMC-VideoReID\
               --batch-size 8\
               --gpu-devices 0,1\
               -a pcb_p6\
               --max-epoch 100\
               --train-sampler RandomIdentitySampler
               #--loss triplet \
```
This lines works well, but once I uncomment the final line to apply softmax-triplet combined loss, it come into troubles:
```python
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    main()
  File "main.py", line 129, in main
    engine.run(**engine_run_kwargs(args))
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torchreid-0.7.2-py2.7-linux-x86_64.egg/torchreid/engine/engine.py", line 100, in run
    self.train(epoch, trainloader, print_freq=print_freq)
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torchreid-0.7.2-py2.7-linux-x86_64.egg/torchreid/engine/image/triplet.py", line 119, in train
    outputs, features = self.model(imgs)
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/cluster/home/it_stu4/.conda/envs/python27/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got input of size [4, 15, 3, 256, 128] instead
```
Are there potential bugs in the codes, or my configurations is in conflict or some necessary configuration missed?

**Comment by KaiyangZhou** [comment]
@WannaSeaU I tried your command and found no error happening. From your traceback I guess you use image engine for processing video data. Set `--app video` (it seems like your provided command does not align with the error log, can you show the full log?)

**Comment by WannaSeaU** [comment]
The output log is:
```
==========
Args:Namespace(adam_beta1=0.9, adam_beta2=0.999, app='video', arch='pcb_p6', base_lr_mult=0.1, batch_size=8, color_aug=False, color_jitter=False, combineall=False, cuhk03_classic_split=False, cuhk03_labeled=False, dist_metric='euclidean', eval_freq=-1, evaluate=False, fixbase_epoch=0, gamma=0.1, gpu_devices='0,1', height=256, label_smooth=False, load_weights='', loss='triplet', lr=0.0003, lr_scheduler='multi_step', margin=0.3, market1501_500k=False, max_epoch=100, momentum=0.9, new_layers=['classifier'], no_pretrained=False, num_instances=4, open_layers=['classifier'], optim='adam', pooling_method='avg', print_freq=10, random_erase=False, ranks=[1, 5, 10, 20], resume='', rmsprop_alpha=0.99, root='../../dataset/DukeMTMC-VideoReID', sample_method='evenly', save_dir='log/pcb-DukeMTMC-VideoReID-combined', seed=1, seq_len=15, sgd_dampening=0, sgd_nesterov=False, sources=['dukemtmcvidreid'], split_id=0, staged_lr=False, start_epoch=0, start_eval=0, stepsize=[20, 40], targets=['dukemtmcvidreid'], train_sampler='RandomIdentitySampler', use_avai_gpus=False, use_cpu=False, use_metric_cuhk03=False, visrank=False, visrank_topk=20, weight_decay=0.0005, weight_t=1, weight_x=1, width=128, workers=4)
==========
Currently using GPU 0,1
=> Loading train (source) dataset
=> Loaded DukeMTMCVidReID
  -------------------------------------------
  subset   | # ids | # tracklets | # cameras
  -------------------------------------------
  train    |   702 |        2196 |         8
  query    |   702 |         702 |         8
  gallery  |  1110 |        2636 |         8
  -------------------------------------------
=> Loading test (target) dataset
=> Loaded DukeMTMCVidReID
  -------------------------------------------
  subset   | # ids | # tracklets | # cameras
  -------------------------------------------
  train    |   702 |        2196 |         8
  query    |   702 |         702 |         8
  gallery  |  1110 |        2636 |         8
  -------------------------------------------


  **************** Summary ****************
  train             : ['dukemtmcvidreid']
  # train datasets  : 1
  # train ids       : 702
  # train tracklets : 2196
  # train cameras   : 8
  test              : ['dukemtmcvidreid']
  *****************************************


Initializing model: pcb_p6
Initialized model with pretrained weights from https://download.pytorch.org/models/resnet50-19c8e357.pth
Initializing optimizer: adam
Initializing lr_scheduler: multi_step
Building triplet-engine for video-reid
=> Start training
```

**Comment by KaiyangZhou** [comment]
Indeed there is an error https://github.com/KaiyangZhou/deep-person-reid/commit/12f9fec96073692b647a0a485a6274b2900db27f. It has been fixed. Please pull the latest commit.

**Comment by WannaSeaU** [comment]
Thanks for your kindness and awesome work!


 
---Original---
