### ISSUE TITLE
Getting error while feeding custom dataset

### ISSUE THREAD

**Issue by Rajat-Mehta** [KaiyangZhou/deep-person-reid#190]
I want to train the reidentification model on VeRi vehicle dataset. I followed the instructions given here on how to use custom dataset: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset 

When I try to train "hacnn" model on this custom (VeRi) dataset, I am not able to train the model. Please find below the dataset statistics and the error that I am getting:

```
=> Loading train (source) dataset
=> Loaded VeRiDataset
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   575 |    37746 |        20
  query    |   200 |     1678 |        19
  gallery  |   200 |    11579 |        19
  ----------------------------------------
=> Loading test (target) dataset
=> Loaded VeRiDataset
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   575 |    37746 |        20
  query    |   200 |     1678 |        19
  gallery  |   200 |    11579 |        19
  ----------------------------------------


  **************** Summary ****************
  train            : ['veri_dataset']
  # train datasets : 1
  # train ids      : 575
  # train images   : 37746
  # train cameras  : 20
  test             : ['veri_dataset']
  *****************************************


=> Start training
/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torch/nn/functional.py:2457: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Traceback (most recent call last):
  File "train_torchreid.py", line 52, in <module>
    print_freq=10
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torchreid-0.7.8-py3.6-linux-x86_64.egg/torchreid/engine/engine.py", line 100, in run
    self.train(epoch, max_epoch, trainloader, fixbase_epoch, open_layers, print_freq)
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torchreid-0.7.8-py3.6-linux-x86_64.egg/torchreid/engine/image/softmax.py", line 99, in train
    loss = self._compute_loss(self.criterion, outputs, pids)
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torchreid-0.7.8-py3.6-linux-x86_64.egg/torchreid/engine/engine.py", line 302, in _compute_loss
    loss = DeepSupervision(criterion, outputs, targets)
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torchreid-0.7.8-py3.6-linux-x86_64.egg/torchreid/losses/__init__.py", line 21, in DeepSupervision
    loss += criterion(x, y)
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rajat/MyPC/DFKI/MasterThesis/Vehicle_Reidentification/veri/lib/python3.6/site-packages/torchreid-0.7.8-py3.6-linux-x86_64.egg/torchreid/losses/cross_entropy_loss.py", line 47, in forward
    targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:551
```

Note: The same code is working fine if I use "market1501" dataset instead of my custom one.

Please help me in solving this issue. 

Thanks

**Comment by KaiyangZhou** [comment]
the error seems to be caused by the mismatch between `num_classes` and label index, try
```
labelset = []
for data, label in dataloader:
    label = label.data.numpy().tolist()
    labelset += label
labelset = set(labelset)
print(labelset)
```
and see if the largest class index is 574 (as your `num_classes=575`)

**Comment by Rajat-Mehta** [comment]
From where do I get this dataloader (on which you are iterating)? 

BTW, Here is the code that I am using to train my model:


```
import torch
import torchreid

datamanager = torchreid.data.ImageDataManager(
    root='../Datsets/VeRi_with_plate/',
    sources='veri_dataset',
    height=160,
    width=64
)
model = torchreid.models.build_model(
    name='hacnn',
    num_classes=datamanager.num_train_pids,
    loss='softmax'
)
model = model.cuda()
optimizer = torchreid.optim.build_optimizer(
    model, optim='adam', lr=0.0003
)
scheduler = torchreid.optim.build_lr_scheduler(
    optimizer,
    lr_scheduler='single_step',
    stepsize=20
)
engine = torchreid.engine.ImageSoftmaxEngine(
    datamanager, model, optimizer, scheduler=scheduler
)
engine.run(
    max_epoch=60,
    save_dir='./model/hacnn',
    print_freq=10
)
```

**Comment by chunniunai220ml** [comment]
I have the same question, do you slove it? @Rajat-Mehta  @KaiyangZhou

**Comment by Rajat-Mehta** [comment]
@KaiyangZhou I tried the following lines of code to print labelset:


```
data_loader, _ = datamanager.return_dataloaders()

labelset = []
for data, label, camera, path in data_loader:
    label = label.data.numpy().tolist()
    labelset += label
labelset = set(labelset)
print(labelset)
print("Number of classes:", labelset)
```

And it outputs a set containing all of the labels belonging to the train set. The number of classes in train set are 575 but the maximum class id is 769. Because there are 776(1 - 776) classes in total, out of which 200 random classes are selected for test set and the remaining 575 for the training set. Here's how the output of above script looks like:

```
{1, 3, 4, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 31, 32, 33, 34, 36, 37, 39, 40, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 62, 64, 67, 68, 69, 70, 71, 72, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 91, 92, 93, 94, 95, 97, 98, 99, 100, 103, 107, 109, 111, 112, 114, 115, 116, 119, 120, 121, 123, 124, 125, 127, 128, 131, 133, 136, 137, 138, 139, 140, 141, 146, 147, 148, 149, 152, 153, 155, 156, 157, 158, 159, 160, 161, 163, 164, 165, 167, 168, 169, 170, 171, 175, 176, 178, 181, 184, 185, 186, 187, 189, 190, 191, 193, 194, 195, 198, 199, 200, 201, 202, 203, 204, 206, 208, 209, 210, 211, 212, 213, 214, 215, 217, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 234, 235, 236, 238, 239, 242, 243, 244, 245, 246, 248, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 274, 275, 276, 277, 278, 279, 280, 282, 283, 284, 285, 286, 287, 289, 290, 291, 292, 293, 297, 301, 302, 303, 304, 305, 307, 308, 309, 311, 312, 313, 314, 316, 317, 320, 321, 323, 324, 325, 328, 329, 330, 331, 333, 334, 335, 336, 338, 339, 340, 341, 342, 343, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 358, 359, 360, 362, 363, 364, 366, 367, 370, 372, 374, 375, 376, 377, 378, 379, 381, 382, 383, 384, 386, 387, 390, 393, 394, 395, 396, 397, 399, 400, 401, 403, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 419, 422, 423, 424, 425, 426, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 447, 448, 449, 451, 452, 453, 454, 455, 457, 458, 459, 460, 462, 463, 464, 465, 466, 468, 469, 470, 471, 472, 474, 475, 478, 479, 481, 483, 484, 487, 488, 490, 491, 492, 493, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 508, 509, 511, 512, 513, 514, 516, 517, 519, 520, 521, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 542, 544, 547, 548, 549, 550, 551, 552, 553, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 567, 568, 571, 572, 573, 574, 575, 577, 578, 579, 580, 583, 587, 589, 591, 592, 594, 595, 596, 599, 600, 601, 603, 604, 605, 607, 608, 611, 613, 616, 617, 618, 619, 620, 621, 626, 627, 628, 629, 632, 633, 635, 636, 637, 638, 639, 640, 641, 643, 644, 645, 647, 648, 649, 650, 651, 655, 656, 658, 661, 664, 665, 666, 667, 669, 670, 671, 673, 674, 675, 678, 679, 680, 681, 682, 683, 684, 686, 688, 689, 690, 691, 692, 693, 694, 695, 697, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 713, 714, 715, 716, 718, 719, 722, 723, 724, 725, 726, 728, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 754, 755, 756, 757, 758, 759, 760, 762, 763, 764, 765, 766, 767, 769}

Number of classes: 575
```

**Comment by KaiyangZhou** [comment]
you need to relabel the training images so that the label starts from 0 and increments by 1 (think about how the classification layer is constructed and how a one-hot vector is generated given an index)
e.g.
raw_label=>new_label
1=>0
3=>1
4=>2
7=>3
8=>4

there is one simple way to convert the label
```python
label_dict = {label: index for index, label in enumerate(labelset)}
new_label = label_dict[raw_label]
```

**Comment by Rajat-Mehta** [comment]
@KaiyangZhou I did the changes as suggested by you and it worked perfectly. Thank you :)

**Comment by kojingying** [comment]
@Rajat-Mehta Can I know where u add in the code and how you add in?
