### ISSUE TITLE
OSNet training error

### ISSUE THREAD

**Issue by johnzhang1999** [KaiyangZhou/deep-person-reid#204]
I got the below error message when trying to train osnet. Not sure what caused it.

```shell
=> Start training
* Only train ['classifier'] (epoch: 1/10)
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    main()
  File "main.py", line 164, in main
    engine.run(**engine_run_kwargs(args))
  File "/home/guest/mvb/deep-person-reid/torchreid/engine/engine.py", line 119, in run
    self.train(epoch, max_epoch, trainloader, fixbase_epoch, open_layers, print_freq)
  File "/home/guest/mvb/deep-person-reid/torchreid/engine/image/softmax.py", line 89, in train
    for batch_idx, data in enumerate(trainloader):
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/guest/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 808 and 552 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:711
```

**Comment by johnzhang1999** [comment]
resolved by adding `random_crop` to the `--transforms` flag.

**Comment by KaiyangZhou** [comment]
this has been resolved, pls pull the latest commit (only using `random_flip` works now)
