### ISSUE TITLE
Memory size required for Market1501-500k

### ISSUE THREAD

**Issue by crossknight** [KaiyangZhou/deep-person-reid#205]
Hi,

I have trained models on Market1501-500k but it used all memory free space on evaluating process and made the machine freeze due to out-of-memory problem.

I have 48gb of RAM. Is it enough?

or did I do something wrong? this is the parameters I use to train the model.

```
python scripts/main.py \
--root $DATA \
--app image \
--loss softmax \
--label-smooth \
-s market1501 \
--market1501-500k \
-a resnet50_fc512 \
--optim adam \
--lr 0.0003 \
--max-epoch 60 \
--stepsize 20 40 \
--batch-size 32 \
--save-dir log/model-market1501-softmax \
--gpu-devices 0

**Comment by gceboh** [comment]
try to decrease `batch-size`,
use more gpu devices `--gpu-devices 0,1,2`

**Comment by crossknight** [comment]
Hi @gceboh,

Does batch-size effect machine memory? not just GPU memory?

**Comment by gceboh** [comment]
Please try other dataset , like `Market1501` and `MSMT17` , and see whether this error happens again.
Also, observe the memory usage of different dataset.

**Comment by crossknight** [comment]
Market1501 and MSMT17 are working fine

**Comment by gceboh** [comment]
Gallery Size:
Market1501 + 500k: 19,732 + 500,000
MSMT17: 93,820

So,the memory usage of 'Market1501 + 500k' may be approximately 5 times larger than 'MSMT17' when evaluating.

**Comment by crossknight** [comment]
So there is no other way except for increasing RAM size?

**Comment by gceboh** [comment]
Increase linux Swap Space may be helpful.

**Comment by crossknight** [comment]
I extended swap space to 50gb still got error

```
Extracting features from query set ...
Done, obtained 3368-by-512 matrix
Extracting features from gallery set ...
Traceback (most recent call last):
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 681, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/crossvis/.pyenv/versions/3.6.7/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/main.py", line 139, in <module>
    main()
  File "scripts/main.py", line 135, in main
    engine.run(**engine_run_kwargs(args))
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torchreid/engine/engine.py", line 127, in run
    ranks=ranks
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torchreid/engine/engine.py", line 206, in test
    rerank=rerank
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 45, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torchreid/engine/engine.py", line 241, in _evaluate
    for batch_idx, data in enumerate(galleryloader):
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in __next__
    idx, data = self._get_data()
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 718, in _get_data
    success, data = self._try_get_data()
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 689, in _try_get_data
    if self.workers_status[worker_id] and not w.is_alive():
  File "/home/crossvis/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/process.py", line 139, in is_alive
    returncode = self._popen.poll()
  File "/home/crossvis/.pyenv/versions/reid/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 19519) is killed by signal: Killed.
```

**Comment by gceboh** [comment]
It used more than 200 GB (virtual memory +physical memory), and still growing...
The evaluation process is too slow, and I don't have enough time to wait for it until complete.

**Comment by crossknight** [comment]
wow... that’s more than I expected
