### ISSUE TITLE
AssertionError: Tensors not supported in scatter.

### ISSUE THREAD

**Issue by yancccc** [KaiyangZhou/deep-person-reid#22]
I've met python error:
==> Start training
Traceback (most recent call last):
  File "train_img_model_xent.py", line 299, in <module>
    main()
  File "train_img_model_xent.py", line 167, in main
    train(epoch, model, criterion, optimizer, trainloader, use_gpu)
  File "train_img_model_xent.py", line 212, in train
    outputs = model(imgs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 69, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 80, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 38, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 31, in scatter
    return scatter_map(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 16, in scatter_map
    assert not torch.is_tensor(obj), "Tensors not supported in scatter."
AssertionError: Tensors not supported in scatter.

**Comment by distant1219** [comment]
I have same problem. What's your train batch size?Or is your pytorch version is 0.4.0. Because at 0.4.0, `Variable` is merged with `Tensor`. If your pytorch version is lower than 0.4.0, you might change `Tensor` to `Variable`

**Comment by KaiyangZhou** [comment]
yea, it looks like you r using the old pytorch.

**Comment by hondaathma** [comment]
if anyone else has this issue the solution is to set your cuda path:
export PATH=$PATH:/usr/local/cuda/bin then do make.sh
