### ISSUE TITLE
Directly using a method's forward() raises NotImplementedError

### ISSUE THREAD

**Issue by JakeCowton** [KaiyangZhou/deep-person-reid#220]
I built [this class](https://gitlab.com/snippets/1891077) to load in a trained `torchreid` model. However, I cannot use the `forward()` method of the model. The specific method used is `mlfn`.

```
reid = RedIDModel("/a/path", "/another/path")
reid.model.forward(a_tensor)

Traceback (most recent call last):
  File "verify_tracks.py", line 32, in <module>
    reid.model.forward(tns)
  File "/home/jake/.virtualenvs/track-verification/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/jake/.virtualenvs/track-verification/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jake/.virtualenvs/track-verification/lib/python3.7/site-packages/torch/nn/modules/module.py", line 103, in forward
    raise NotImplementedError
NotImplementedError
```

**Comment by JakeCowton** [comment]
Ignore this. This was a foolish mistake on my part. Thank you for being a good rubber duck!
