### ISSUE TITLE
cross_entropy_loss error

### ISSUE THREAD

**Issue by universea** [KaiyangZhou/deep-person-reid#250]
=> Start training
log_probs.shape =  torch.Size([32, 4556])
targets.shape =  torch.Size([32])
Traceback (most recent call last):
  File "scripts/train.py", line 52, in <module>
    test_only=False
  File "/home/airobot/kesci/reid/deep-person-reid/torchreid/engine/engine.py", line 114, in run
    self.train(epoch, max_epoch, trainloader, fixbase_epoch, open_layers, print_freq)
  File "/home/airobot/kesci/reid/deep-person-reid/torchreid/engine/image/softmax.py", line 96, in train
    loss = self._compute_loss(self.criterion, outputs, pids)
  File "/home/airobot/kesci/reid/deep-person-reid/torchreid/engine/engine.py", line 387, in _compute_loss
    loss = criterion(outputs, targets)
  File "/home/airobot/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/airobot/kesci/reid/deep-person-reid/torchreid/losses/cross_entropy_loss.py", line 50, in forward
    targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151

**Comment by MaggieeeChen** [comment]
Hey, I encountered same question when I applied the code on VeRi-776. Would you like to share your solution? Many thx!
