### ISSUE TITLE
when set fixbase_epoch to 0, the error occurs

### ISSUE THREAD

**Issue by s2244521** [KaiyangZhou/deep-person-reid#340]
I set the fixbase_epoch to 0 and the error occurs.
The program stops at 
"Building model: osnet_x1_0
Model complexity: params=2,193,616 flops=978,878,352
Building softmax-engine for image-reid
=> Start training"
I use this script "python scripts/main.py --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml --transforms random_flip random_erase --root "data_path"

**Comment by KaiyangZhou** [comment]
what's the full command to reproduce your error?

**Comment by KaiyangZhou** [comment]
what's the error? and what's your system setup?

**Comment by s2244521** [comment]
The program stops at "Start training" and no training inform to be printed.
Here is my script
model:
  name: 'osnet_x1_0'
  pretrained: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_x1_0_market1501_softmax_cosinelr'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 5
  batch_size: 64
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False

**Comment by KaiyangZhou** [comment]
hmm, that's weird

I ran the following command and found no error at all
```bash
python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
--transforms random_flip random_erase \
--root $DATA/reid \
train.print_freq 1 \
train.fixbase_epoch 0 \
data.save_dir log/tmp
```

It'd be more helpful if you could provide more info for debugging, e.g. system setup, gpu, ...

**Comment by s2244521** [comment]
My environmental setting is win10, python3.7.7 and cuda9.0.
If I modify the yaml parameters, should I need to write these changed parameters in my script?
ex: python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
--transforms random_flip random_erase \
--root $DATA/reid \
""train.print_freq 1 \
train.fixbase_epoch 0 \""

**Comment by KaiyangZhou** [comment]
so is `fixbase_epoch=0` still giving you error?

you don't need to create a new yaml to change the arguments, the quickest way is to append the changes at the end of input arguments

see this https://github.com/KaiyangZhou/deep-person-reid/blob/master/scripts/main.py

**Comment by s2244521** [comment]
Yes. I used the script "im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml"  and didn't change any content but it stopped at the epoch 10, the training process didn't continue. It seems that the open_all_layers can't work well. Someone met this issue and you gave a advice that is to set the print freq as 1, I did it but it still can't work.

**Comment by KaiyangZhou** [comment]
that's a bit weird

I'm not familiar with your setting, maybe let's do some quick debugging

after you pull this repo and do the installation, run
```bash
python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
--transforms random_flip random_erase \
--root $DATA/reid \
train.print_freq 1 \
train.fixbase_epoch 1 \
train.max_epoch 3 \
data.save_dir log/tmp
```

what is the output?

**Comment by s2244521** [comment]
What is your environmental setting (pytorch and pytorchvision)?
I renew my environment to pytorch1.1.0, pytorchvision0.3.0, python3.7.7 and cuda9.0 and my os is win10.
I run the script you recommended, here is the result
Collecting env info ...
Traceback (most recent call last):
  File "scripts/main.py", line 184, in <module>
    main()
  File "scripts/main.py", line 140, in main
    print('** System info **\n{}\n'.format(collect_env_info()))
  File "d:\user_data\tina\osnet\torchreid\utils\tools.py", line 127, in collect_env_info
    env_str = get_pretty_env_info()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\collect_env.py", line 376, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\collect_env.py", line 273, in get_env_info
    conda_packages=get_conda_packages(run_lambda),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\collect_env.py", line 75, in get_conda_packages
    out = run_and_read_all(run_lambda, conda + ' list | ' + grep_cmd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\collect_env.py", line 52, in run_and_read_all
    rc, out, _ = run_lambda(command)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\collect_env.py", line 46, in run
    err = err.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 8: invalid start byte

**Comment by KaiyangZhou** [comment]
it works on `torch>=0.4` and `torchvision>=0.1`

looks like the code stops at https://github.com/KaiyangZhou/deep-person-reid/blob/b2e956cabdb134d8f3fcd2c54e1d4d7d77d89c36/torchreid/utils/tools.py#L121

it seems to be a windows problem? maybe this helps https://github.com/KaiyangZhou/deep-person-reid/issues/333

**Comment by s2244521** [comment]
I reset my environment to cuda10, pytorch1.1.0 and torchvision0.3.0 and it works well under your script. I think that my GPU is Ti2080, it needs the cuda version 10+ or the operation can't work well. Many thanks for your code and enthusiastic help.
