### ISSUE TITLE
RuntimeError: cublas runtime error

### ISSUE THREAD

**Issue by sopsos** [KaiyangZhou/deep-person-reid#375]
I am getting this error
```
(torchreid) $ python scripts/main.py \
> --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
> --transforms random_flip random_erase \
> --root $PATH_TO_DATA
Show configuration
adam:
  beta1: 0.9
  beta2: 0.999
cuhk03:
  classic_split: False
  labeled_images: False
  use_metric_cuhk03: False
data:
  combineall: False
  height: 256
  k_tfm: 1
  load_train_targets: False
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  root: /home/me/code/tmp/deep-person-reid/data
  save_dir: log/osnet_x1_0_market1501_softmax_cosinelr
  sources: ['market1501']
  split_id: 0
  targets: ['market1501']
  transforms: ['random_flip', 'random_erase']
  type: image
  width: 128
  workers: 4
loss:
  name: softmax
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 1.0
    weight_x: 0.0
market1501:
  use_500k_distractors: False
model:
  load_weights: 
  name: osnet_x1_0
  pretrained: True
  resume: 
rmsprop:
  alpha: 0.99
sampler:
  num_cams: 1
  num_datasets: 1
  num_instances: 4
  train_sampler: RandomSampler
  train_sampler_t: RandomSampler
sgd:
  dampening: 0.0
  momentum: 0.9
  nesterov: False
test:
  batch_size: 300
  dist_metric: euclidean
  eval_freq: -1
  evaluate: False
  normalize_feature: False
  ranks: [1, 5, 10, 20]
  rerank: False
  start_eval: 0
  visrank: False
  visrank_topk: 10
train:
  base_lr_mult: 0.1
  batch_size: 64
  fixbase_epoch: 10
  gamma: 0.1
  lr: 0.0015
  lr_scheduler: cosine
  max_epoch: 250
  new_layers: ['classifier']
  open_layers: ['classifier']
  optim: amsgrad
  print_freq: 20
  seed: 1
  staged_lr: False
  start_epoch: 0
  stepsize: [20]
  weight_decay: 0.0005
use_gpu: True
video:
  pooling_method: avg
  sample_method: evenly
  seq_len: 15

Collecting env info ...
** System info **
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.1.0
[pip3] torchreid==1.3.3
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torchreid                 1.3.3                     dev_0    <develop>
[conda] torchvision               0.3.0           py37_cu9.0.176_1    pytorch
        Pillow (7.2.0)

Building train transforms ...
+ resize to 256x128
+ random flip
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
+ random erase
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------
=> Loading test (target) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------


  **************** Summary ****************
  source            : ['market1501']
  # source datasets : 1
  # source ids      : 751
  # source images   : 12936
  # source cameras  : 6
  target            : ['market1501']
  *****************************************


Building model: osnet_x1_0
Successfully loaded imagenet pretrained weights from "/home/me/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Model complexity: params=2,193,616 flops=978,878,352
Building softmax-engine for image-reid
=> Start training
* Only train ['classifier'] (epoch: 1/10)
Traceback (most recent call last):
  File "scripts/main.py", line 191, in <module>
    main()
  File "scripts/main.py", line 187, in main
    engine.run(**engine_run_kwargs(cfg))
  File "/home/me/code/deep-person-reid/torchreid/engine/engine.py", line 193, in run
    open_layers=open_layers
  File "/home/me/code/deep-person-reid/torchreid/engine/engine.py", line 245, in train
    loss_summary = self.forward_backward(data)
  File "/home/me/code/deep-person-reid/torchreid/engine/image/softmax.py", line 85, in forward_backward
    outputs = self.model(imgs)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/code/deep-person-reid/torchreid/models/osnet.py", line 429, in forward
    v = self.fc(v)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/me/.conda/envs/torchreid/lib/python3.7/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:259
```

What worries me is that I did not install conda in `/opt/conda` but in `/usr/local/miniconda3/condabin/conda`. However conda works perfectly.

To reproduce it, one just needs to install it following the README's instructions:
```
# cd to your preferred directory and clone this repo
git clone https://github.com/KaiyangZhou/deep-person-reid.git

# create environment
cd deep-person-reid/
conda create --name torchreid python=3.7
conda activate torchreid

# install dependencies
# make sure `which python` and `which pip` point to the correct path
pip install -r requirements.txt

# install torch and torchvision (select the proper cuda version to suit your machine)
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

# install torchreid (don't need to re-build it if you modify the source code)
python setup.py develop

# added by me
PATH_TO_DATA="/somewhere_accessible"
mkdir -p $PATH_TO_DATA
```

Here's my conda environment
```
(torchreid) $ conda list
# packages in environment at /home/me/.conda/envs/torchreid:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.10.0                   pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.7.22                     0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0  
cffi                      1.14.3           py37he30daa8_0  
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               9.0                  h13b8566_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.8.3                    pypi_0    pypi
freetype                  2.10.2               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
gdown                     3.12.2                   pypi_0    pypi
google-auth               1.21.3                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        2.0.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.2.0                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
lz4-c                     1.9.2                he6710b0_1  
markdown                  3.2.2                    pypi_0    pypi
matplotlib                3.3.2                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.1           py37hfd86e86_0  
numpy                     1.19.2                   pypi_0    pypi
numpy-base                1.19.1           py37hfa32c7d_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.4.0.44                 pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
pillow                    7.2.0            py37hb39fc2d_0  
pip                       20.2.2                   py37_0  
protobuf                  3.13.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyflakes                  2.2.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
setuptools                49.6.0                   py37_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
tb-nightly                2.4.0a20200921           pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torchreid                 1.3.3                     dev_0    <develop>
torchvision               0.3.0           py37_cu9.0.176_1    pytorch
tqdm                      4.49.0                   pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
yapf                      0.30.0                   pypi_0    pypi
zipp                      3.2.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

**Comment by sopsos** [comment]
I fixed it by installing CUDA 10 instead of 9. It seems my graphics card (RTX 2080) requires at least CUDA 10, but the installation doesn't complain about that. The installation instructions should say
`conda install pytorch torchvision cudatoolkit=10 -c pytorch`

Is there any reason why torchreid requires CUDA 9?

**Comment by KaiyangZhou** [comment]
the error should be caused by the mismatched cuda version, rather than by the code
