### ISSUE TITLE
Couldn't open shared file mapping: <torch_12372_2591263215>, error code: <1455>

### ISSUE THREAD

**Issue by ww5171351** [KaiyangZhou/deep-person-reid#389]
训练完成后，出现如下警报
=> Final test最终试验
##### Evaluating market1501 (source) #####
Extracting features from query set ...
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
Done, obtained 3368-by-512 matrix
Extracting features from gallery set ...
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
H:\Code in the paper\deep-person-reid-master\torchreid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.Cython求值（非常快，因此强烈建议）不可用，现在使用python求值。
  'Cython evaluation (very fast so highly recommended) is '
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    main()
  File "main.py", line 209, in main
    engine.run(**engine_run_kwargs(cfg))
  File "H:\Code in the paper\deep-person-reid-master\torchreid\engine\engine.py", line 220, in run
    ranks=ranks
  File "H:\Code in the paper\deep-person-reid-master\torchreid\engine\engine.py", line 335, in test
    rerank=rerank
  File "F:\Python37\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "H:\Code in the paper\deep-person-reid-master\torchreid\engine\engine.py", line 384, in _evaluate
    gf, g_pids, g_camids = _feature_extraction(gallery_loader)
  File "H:\Code in the paper\deep-person-reid-master\torchreid\engine\engine.py", line 363, in _feature_extraction
    for batch_idx, data in enumerate(data_loader):
  File "F:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "F:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "F:\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "F:\Python37\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "F:\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "F:\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "F:\Python37\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "F:\Python37\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "F:\Python37\lib\site-packages\torch\utils\data\_utils\collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "F:\Python37\lib\site-packages\torch\storage.py", line 136, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_12372_2591263215>, error code: <1455>

**Comment by KaiyangZhou** [comment]
it's an error from the pytorch code

a simple google search on "RuntimeError: Couldn't open shared file mapping" should give you useful information
https://github.com/pytorch/pytorch/issues/18797
https://github.com/pytorch/pytorch/issues/31874

**Comment by ww5171351** [comment]
感谢您在百忙之中的回复，您发的两个链接，我详细看了，可能是因为我水平有限，没怎么看懂这上面的解决方法。您能稍微详细的指点一下，怎么解决吗
