### ISSUE TITLE
"torchreid\metrics\rank_cylib\rank_cy.pyx"  didn't work in Windows----ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by tomFoxxxx** [KaiyangZhou/deep-person-reid#408]
When I try to evaluate the model effect:
----------------------------------------------------
##### Evaluating market1501 (source) #####
Extracting features from query set ...
Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...
Done, obtained 15913-by-2048 matrix
Speed: 0.0258 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
----------------------------------------------------
Traceback (most recent call last):
  File "induction.py", line 67, in <module>
    main()
  File "induction.py", line 62, in main
    test_only=False
  File "d:\pycharm\ha-cnn_reid\deep-person-reid\torchreid\engine\engine.py", line 207, in run
    ranks=ranks
  File "d:\pycharm\ha-cnn_reid\deep-person-reid\torchreid\engine\engine.py", line 335, in test
    rerank=rerank
  File "D:\anaconda_home\envs\general\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "d:\pycharm\ha-cnn_reid\deep-person-reid\torchreid\engine\engine.py", line 413, in _evaluate
    use_metric_cuhk03=use_metric_cuhk03
  File "d:\pycharm\ha-cnn_reid\deep-person-reid\torchreid\metrics\rank.py", line 201, in evaluate_rank
    use_metric_cuhk03
  File "torchreid\metrics\rank_cylib\rank_cy.pyx", line 25, in torchreid.metrics.rank_cylib.rank_cy.evaluate_cy
  File "torchreid\metrics\rank_cylib\rank_cy.pyx", line 33, in torchreid.metrics.rank_cylib.rank_cy.evaluate_cy
**ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'**

_So, how should I change this file to fit the correct datatype?_

cpdef eval_market1501_cy(float[:,:] distmat, long[:] q_pids, long[:]g_pids,
                         long[:]q_camids, long[:]g_camids, long max_rank):
--->
cpdef eval_market1501_cy(float[:,:] distmat, longlong[:] q_pids, longlong[:]g_pids,
                         longlong[:]q_camids, longlong[:]g_camids, longlong max_rank):

**It's this right?**

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues/391

**Comment by tomFoxxxx** [comment]
> #391

thanks for your technique assistant.
