### ISSUE TITLE
Simple problem

### ISSUE THREAD

**Issue by Easybuddys** [KaiyangZhou/deep-person-reid#419]
I'm using Win10.
Collecting env info ...
Traceback (most recent call last):
  File "scripts/main.py", line 185, in <module>
    main()
  File "scripts/main.py", line 141, in main
    print('** System info **\n{}\n'.format(collect_env_info()))
  File "d:\archive\cplusplus-project\deep-person-reid-master\deep-person-reid-master\torchreid\utils\tools.py", line 127, in collect_env_info
    env_str = get_pretty_env_info()
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 376, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 274, in get_env_info
    os=get_os(run_lambda),
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 194, in get_os
    return get_windows_version(run_lambda)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 178, in get_windows_version
    return run_and_read_all(run_lambda, 'wmic os get Caption | findstr /v Caption')
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 52, in run_and_read_all
    rc, out, _ = run_lambda(command)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 45, in run
    output = output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 25: invalid start byte

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues?q=UnicodeDecodeError

**Comment by Easybuddys** [comment]
Sorry, it's still useless.

**Comment by Easybuddys** [comment]
Collecting env info ...
Traceback (most recent call last):
  File "scripts/main.py", line 185, in <module>
    main()
  File "scripts/main.py", line 141, in main
    print('** System info **\n{}\n'.format(collect_env_info()))
  File "d:\archive\cplusplus-project\deep-person-reid-master\deep-person-reid-master\torchreid\utils\tools.py", line 127, in collect_env_info
    env_str = get_pretty_env_info()
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 376, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 274, in get_env_info
    os=get_os(run_lambda),
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 194, in get_os
    return get_windows_version(run_lambda)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 178, in get_windows_version
    return run_and_read_all(run_lambda, 'wmic os get Caption | findstr /v Caption')
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 52, in run_and_read_all
    rc, out, _ = run_lambda(command)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 45, in run
    output = output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 25: invalid start byte

**Comment by Easybuddys** [comment]
> Collecting env info ...
> Traceback (most recent call last):
> File "scripts/main.py", line 185, in
> main()
> File "scripts/main.py", line 141, in main
> print('** System info **\n{}\n'.format(collect_env_info()))
> File "d:\archive\cplusplus-project\deep-person-reid-master\deep-person-reid-master\torchreid\utils\tools.py", line 127, in collect_env_info
> env_str = get_pretty_env_info()
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 376, in get_pretty_env_info
> return pretty_str(get_env_info())
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 274, in get_env_info
> os=get_os(run_lambda),
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 194, in get_os
> return get_windows_version(run_lambda)
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 178, in get_windows_version
> return run_and_read_all(run_lambda, 'wmic os get Caption | findstr /v Caption')
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 52, in run_and_read_all
> rc, out, _ = run_lambda(command)
> File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 45, in run
> output = output.decode("utf-8")
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 25: invalid start byte

**Comment by Easybuddys** [comment]
D:\Archive\python\deep-person-reid-dev1\deep-person-reid-dev>python scripts/main.py --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml -s dukemtmcreid -t dukemtmcreid --transforms random_flip random_erase --root D:\Archive\python\deep-person-reid-dev data.save_dir log/osnet_x1_0_dukemtmcreid_softmax_cosinelr
Show configuration
adam:
  beta1: 0.9
  beta2: 0.999
cuhk03:
  classic_split: False
  labeled_images: False
  use_metric_cuhk03: False
data:
  combineall: False
  height: 256
  load_train_targets: False
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  root: D:\Archive\python\deep-person-reid-dev
  save_dir: log/osnet_x1_0_dukemtmcreid_softmax_cosinelr
  sources: ['dukemtmcreid']
  split_id: 0
  targets: ['dukemtmcreid']
  transforms: ['random_flip', 'random_erase']
  type: image
  width: 128
  workers: 4
loss:
  name: softmax
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 1.0
    weight_x: 0.0
market1501:
  use_500k_distractors: False
model:
  load_weights:
  name: osnet_x1_0
  pretrained: True
  resume:
rmsprop:
  alpha: 0.99
sampler:
  num_instances: 4
  train_sampler: RandomSampler
sgd:
  dampening: 0.0
  momentum: 0.9
  nesterov: False
test:
  batch_size: 300
  dist_metric: euclidean
  eval_freq: -1
  evaluate: False
  normalize_feature: False
  ranks: [1, 5, 10, 20]
  rerank: False
  start_eval: 0
  visactmap: False
  visrank: False
  visrank_topk: 10
train:
  base_lr_mult: 0.1
  batch_size: 64
  fixbase_epoch: 10
  gamma: 0.1
  lr: 0.0015
  lr_scheduler: cosine
  max_epoch: 250
  new_layers: ['classifier']
  open_layers: ['classifier']
  optim: amsgrad
  print_freq: 20
  seed: 1
  staged_lr: False
  start_epoch: 0
  stepsize: [20]
  weight_decay: 0.0005
use_gpu: True
video:
  pooling_method: avg
  sample_method: evenly
  seq_len: 15

Collecting env info ...
Traceback (most recent call last):
  File "scripts/main.py", line 185, in <module>
    main()
  File "scripts/main.py", line 141, in main
    print('** System info **\n{}\n'.format(collect_env_info()))
  File "d:\archive\python\deep-person-reid-master\deep-person-reid-master\torchreid\utils\tools.py", line 127, in collect_env_info
    env_str = get_pretty_env_info()
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 376, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 274, in get_env_info
    os=get_os(run_lambda),
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 194, in get_os
    return get_windows_version(run_lambda)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 178, in get_windows_version
    return run_and_read_all(run_lambda, 'wmic os get Caption | findstr /v Caption')
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 52, in run_and_read_all
    rc, out, _ = run_lambda(command)
  File "E:\Programs\Anaconda3-5.3.1\lib\site-packages\torch\utils\collect_env.py", line 45, in run
    output = output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 25: invalid start byte

**Comment by Easybuddys** [comment]
Thank God, I have solved this problem
    I am a Windows environment, using the default data set, that is, I did not manually prepare the data set. At the beginning, I did not specify the Unicode code page, but used the default code page (936) of the windows command line.
    After changing the code page and using your solution, UnicodeDecodeError still appears
Later, I manually prepared the cuhk01 data set and specified it in the command line.
