### ISSUE TITLE
Error when computing CMC and mAP using ./scripts/main.py

### ISSUE THREAD

**Issue by malpeddinilesh** [KaiyangZhou/deep-person-reid#424]
Hi @KaiyangZhou ,

I was trying pre-trained model training with custom datasets. Using ./scripts/main.py, after 20 epochs complete, I am getting following error while computing CMC and mAP.

Any guidance would be helpful.

Computing distance matrix with metric=cosine ...
Computing CMC and mAP ...
distmat shape: (66, 54)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/../deep-person-reid/scripts/main.py", line 196, in <module>
    main()
  File "/../deep-person-reid/scripts/main.py", line 192, in main
    engine.run(**engine_run_kwargs(cfg))
  File "/../deep-person-reid/torchreid/engine/engine.py", line 220, in run
    ranks=ranks
  File "/../deep-person-reid/torchreid/engine/engine.py", line 335, in test
    rerank=rerank
  File "/../anaconda3/envs/newmmpose/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/../deep-person-reid/torchreid/engine/engine.py", line 413, in _evaluate
    use_metric_cuhk03=use_metric_cuhk03
  File "/../deep-person-reid/torchreid/metrics/rank.py", line 208, in evaluate_rank
    use_metric_cuhk03
  File "/../deep-person-reid/torchreid/metrics/rank.py", line 167, in evaluate_py
    distmat, q_pids, g_pids, q_camids, g_camids, max_rank
  File "/../deep-person-reid/torchreid/metrics/rank.py", line 149, in eval_market1501
    all_cmc = np.asarray(all_cmc).astype(np.float32)
ValueError: setting an array element with a sequence.

**Comment by KaiyangZhou** [comment]
I guess the problem might be related to how you constructed the dataset

please check https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset

**Comment by malpeddinilesh** [comment]
Thank you @KaiyangZhou! This issue is resolved and closing.
