### ISSUE TITLE
Error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 1: ordinal not in range(128)" when running the README example with python3

### ISSUE THREAD

**Issue by MuadDev** [KaiyangZhou/deep-person-reid#43]
When I try to run the example as specified in the README, like this:

```bash
python train_imgreid_xent.py -d market1501 -a resnet50 --evaluate --resume saved-models/resnet50_xent_market1501.pth.tar --save-dir log/resnet50-xent-market1501 --test-batch 100 --gpu-devices 0
```
I get the following error:
```bash
Warning: Cython evaluation is UNAVAILABLE
==========
Args:Namespace(arch='resnet50', cuhk03_classic_split=False, cuhk03_labeled=False, dataset='market1501', eval_step=-1, evaluate=True, fixbase_epoch=0, fixbase_lr=0.0003, freeze_bn=False, gamma=0.1, gpu_devices='0', height=256, load_weights='', lr=0.0003, max_epoch=60, optim='adam', print_freq=10, resume='saved-models/resnet50_xent_market1501.pth.tar', root='data', save_dir='log/resnet50-xent-market1501', seed=1, split_id=0, start_epoch=0, start_eval=0, stepsize=[20, 40], test_batch=100, train_batch=32, use_cpu=False, use_lmdb=False, use_metric_cuhk03=False, vis_ranked_res=False, weight_decay=0.0005, width=128, workers=4)
==========
Currently using GPU 0
Initializing dataset market1501
=> Market1501 loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # images
  ------------------------------
  train    |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
  ------------------------------
  total    |  1501 |    32217
  ------------------------------
Initializing model: resnet50
Model size: 23.508 M
Traceback (most recent call last):
  File "train_imgreid_xent.py", line 379, in <module>
    main()
  File "train_imgreid_xent.py", line 196, in main
    checkpoint = torch.load(args.resume)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 1: ordinal not in range(128)

```
It appears that there is something wrong with the reading of the saved model.

A google search yields the following results in this [SO answer](https://stackoverflow.com/a/21190382/8488985). However, this is only valid for python2 not python3 which I am using. (I tried using it but did it did not work)

Is it possible that the code is not python3 compatible? Or is there something else?

**Comment by KaiyangZhou** [comment]
Does this https://github.com/KaiyangZhou/deep-person-reid/issues/3#issuecomment-384883745 help?

**Comment by MuadDev** [comment]
That looks like it does the trick. For now I am using python2.7, which also works.

**Comment by hsuRush** [comment]
A better solution **not** to edit the torch source code, [solution](https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990) from @soravux

```python
  pickle.load = partial(pickle.load, encoding="latin1")
  pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
  checkpoint = torch.load(args.resume,pickle_module=pickle)
```
 197 lines in `train_imgreid_xent.py`

**Comment by hsfzxjy** [comment]
Now should be line 539 for pytorch 0.4.1.
