### ISSUE TITLE
weights load error from "Multi-source domain generalization"

### ISSUE THREAD

**Issue by TxuanYu** [KaiyangZhou/deep-person-reid#440]
```
Unable to load checkpoint from "weights/data.pkl"
Traceback (most recent call last):
  File "D:/Google 雲端資料/MOT/track_front_blue/track.py", line 279, in <module>
    main(opt,seqs)
  File "D:/Google 雲端資料/MOT/track_front_blue/track.py", line 191, in main
    save_dir=image_dir, show_image=opt.show_image, frame_rate=hyp['frame_rate'])
  File "D:/Google 雲端資料/MOT/track_front_blue/track.py", line 80, in eval_seq
    tracker = Tracker(opt, hyp, save_dir, num_feat = opt.num_feat, frame_rate=frame_rate)
  File "D:\Google 雲端資料\MOT\track_front_blue\tracker\multitracker.py", line 257, in __init__
    pretrained=False
  File "D:\Google 雲端資料\MOT\track_front_blue\utils\feature_extractor.py", line 88, in __init__
    load_pretrained_weights(model, model_path)
  File "C:\Users\txuan\Desktop\Github\deep-person-reid\torchreid\utils\torchtools.py", line 272, in load_pretrained_weights
    checkpoint = load_checkpoint(weight_path)
  File "C:\Users\txuan\Desktop\Github\deep-person-reid\torchreid\utils\torchtools.py", line 84, in load_checkpoint
    checkpoint = torch.load(fpath, map_location=map_location)
  File "C:\Users\txuan\Anaconda3\envs\trackv2\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\txuan\Anaconda3\envs\trackv2\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

Process finished with exit code 1
```
Thank you for good work.
when I load the new release weights in "Multi-source domain generalization"
I encounter this problem.
How could I resolve it ?

**Comment by KaiyangZhou** [comment]
can you provide the commands for reproducing this error?

**Comment by TxuanYu** [comment]
I run main.py in scripts, this is commands : 
`python main.py --config-file ../configs/im_osnet_ain_x1_0_softmax_256x128_amsgrad_cosine.yaml -s market1501 -t market1501 --root ../../data model.load_weights data.pkl test.evaluate True `

and error : 
```
Building model: osnet_ain_x1_0
Successfully loaded imagenet pretrained weights from "C:\Users\txuan/.cache\torch\checkpoints\osnet_ain_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Model complexity: params=2,193,616 flops=978,878,352
Unable to load checkpoint from "data.pkl"
Traceback (most recent call last):
  File "main.py", line 191, in <module>
    main()
  File "main.py", line 168, in main
    load_pretrained_weights(model, cfg.model.load_weights)
  File "c:\users\txuan\desktop\github\deep-person-reid\torchreid\utils\torchtools.py", line 272, in load_pretrained_weights
    checkpoint = load_checkpoint(weight_path)
  File "c:\users\txuan\desktop\github\deep-person-reid\torchreid\utils\torchtools.py", line 84, in load_checkpoint
    checkpoint = torch.load(fpath, map_location=map_location)
  File "C:\Users\txuan\Anaconda3\envs\trackv2\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\txuan\Anaconda3\envs\trackv2\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

but if I use other weights like `osnet_ain_x1_0_market1501_256x128_amsgrad_ep100_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth`, I can get result without error

can you provide your pytorch version?

**Comment by KaiyangZhou** [comment]
I see. So the error comes from `data.pkl`. You should refer to `torch.load` to check whether your file is compatible or not
