### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by weizi0807** [KaiyangZhou/deep-person-reid#499]
I use  python scripts/main.py --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml --transforms random_flip random_erase  train.print_freq 1 train.fixbase_epoch 1 train.max_epoch 3 data.save_dir log/tmp

When start training ,the error occurs  on epoch 1 .

Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/data/ccuser1/lfm/zzw/zzw/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/data/ccuser1/anaconda3/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long

**Comment by jxthyatt** [comment]
how did u solve this problem?
