### ISSUE TITLE
Error with input size assertion when running HACNN on Duke MTMC

### ISSUE THREAD

**Issue by MuadDev** [KaiyangZhou/deep-person-reid#50]
When I run HACNN on Duke MTMC using
```
python train_vidreid_xent.py -d dukemtmcvidreid -a hacnn --evaluate --resume saved-models/hacnn_xent_dukemtmcreid.pth.tar --save-dir log/resnet50-xent-dukemtmc --test-batch 2 --gpu-devices 0  
```
I get the following error:
```
Warning: Cython evaluation is UNAVAILABLE
==========
Args:Namespace(arch='hacnn', dataset='dukemtmcvidreid', eval_step=-1, evaluate=True, fixbase_epoch=0, fixbase_lr=0.0003, freeze_bn=False, gamma=0.1, gpu_devices='0', height=256, label_smooth=False, load_weights='', lr=0.0003, max_epoch=15, optim='adam', pool='avg', print_freq=10, resume='saved-models/hacnn_xent_dukemtmcreid.pth.tar', root='data', save_dir='log/resnet50-xent-dukemtmc', seed=1, seq_len=15, start_epoch=0, start_eval=0, stepsize=[20, 40], test_batch=2, train_batch=32, use_cpu=False, vis_ranked_res=False, weight_decay=0.0005, width=128, workers=4)
==========
Currently using GPU 0
Initializing dataset dukemtmcvidreid
This dataset has been downloaded.
Note: if root path is changed, the previously generated json files need to be re-generated (so delete them first)
=> Automatically generating split (might take a while for the first time, have a coffe)
Processing data/dukemtmc-vidreid/DukeMTMC-VideoReID/train with 702 person identities
Saving split to data/dukemtmc-vidreid/split_train.json
=> Automatically generating split (might take a while for the first time, have a coffe)
Processing data/dukemtmc-vidreid/DukeMTMC-VideoReID/query with 702 person identities
Saving split to data/dukemtmc-vidreid/split_query.json
=> Automatically generating split (might take a while for the first time, have a coffe)
Processing data/dukemtmc-vidreid/DukeMTMC-VideoReID/gallery with 1110 person identities
Warn: index name F0001 in data/dukemtmc-vidreid/DukeMTMC-VideoReID/gallery/0002/2197 is missing, jump to next
Saving split to data/dukemtmc-vidreid/split_gallery.json
=> DukeMTMC-VideoReID loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # tracklets
  ------------------------------
  train    |   702 |     2196
  query    |   702 |      702
  gallery  |  1110 |     2636
  ------------------------------
  total    |  1404 |     5534
  number of images per tracklet: 1 ~ 9324, average 167.6
  ------------------------------
Initializing model: hacnn
Model size: 3.649 M
Loaded checkpoint from 'saved-models/hacnn_xent_dukemtmcreid.pth.tar'
- start_epoch: 299
- rank1: 0.8070017695426941
Evaluate only
Traceback (most recent call last):
  File "train_vidreid_xent.py", line 395, in <module>
    main()
  File "train_vidreid_xent.py", line 216, in main
    distmat = test(model, queryloader, galleryloader, args.pool, use_gpu, return_distmat=True)
  File "train_vidreid_xent.py", line 328, in test
    features = model(imgs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/rooijenalv/Projects/gitlab-dv/projects/fietsreid/deployment/external/deep-person-reid/torchreid/models/hacnn.py", line 283, in forward
    "Input size does not match, expected (160, 64) but got ({}, {})".format(x.size(2), x.size(3))
AssertionError: Input size does not match, expected (160, 64) but got (256, 128)

```
How can I fix this?

**Comment by KaiyangZhou** [comment]
the input size to hacnn is 160x64, so you need to add `--height 160 --width 64` to the arguments
