### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.uint16.

### ISSUE THREAD

**Issue by knaticat** [KaiyangZhou/deep-person-reid#506]
Hi @KaiyangZhou!

I am facing this issue after the step: "Extracting features from query set" while training my own re-id dataset structured similar to the MARS dataset.
Could you please let me know a fix to this problem?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-16-133ed93fffae>](https://localhost:8080/#) in <module>()
     46         eval_freq=10,
     47         print_freq=10,
---> 48         test_only=False
     49     )

8 frames
[/content/deep-person-reid/torchreid/engine/engine.py](https://localhost:8080/#) in run(self, save_dir, max_epoch, start_epoch, print_freq, fixbase_epoch, open_layers, start_eval, eval_freq, test_only, dist_metric, normalize_feature, visrank, visrank_topk, use_metric_cuhk03, ranks, rerank)
    205                     save_dir=save_dir,
    206                     use_metric_cuhk03=use_metric_cuhk03,
--> 207                     ranks=ranks
    208                 )
    209                 self.save_model(self.epoch, rank1, save_dir)

[/content/deep-person-reid/torchreid/engine/engine.py](https://localhost:8080/#) in test(self, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
    333                 use_metric_cuhk03=use_metric_cuhk03,
    334                 ranks=ranks,
--> 335                 rerank=rerank
    336             )
    337 

[/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

[/content/deep-person-reid/torchreid/engine/engine.py](https://localhost:8080/#) in _evaluate(self, dataset_name, query_loader, gallery_loader, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
    378 
    379         print('Extracting features from query set ...')
--> 380         qf, q_pids, q_camids = _feature_extraction(query_loader)
    381         qf = qf.astype(np.uint8)
    382         q_pids = q_pids.astype(np.uint8)

[/content/deep-person-reid/torchreid/engine/engine.py](https://localhost:8080/#) in _feature_extraction(data_loader)
    361         def _feature_extraction(data_loader):
    362             f_, pids_, camids_ = [], [], []
--> 363             for batch_idx, data in enumerate(data_loader):
    364                 imgs, pids, camids = self.parse_data_for_eval(data)
    365                 if self.use_gpu:

[/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __next__(self)
    528             if self._sampler_iter is None:
    529                 self._reset()
--> 530             data = self._next_data()
    531             self._num_yielded += 1
    532             if self._dataset_kind == _DatasetKind.Iterable and \

[/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _next_data(self)
   1222             else:
   1223                 del self._task_info[idx]
-> 1224                 return self._process_data(data)
   1225 
   1226     def _try_put_index(self):

[/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _process_data(self, data)
   1248         self._try_put_index()
   1249         if isinstance(data, ExceptionWrapper):
-> 1250             data.reraise()
   1251         return data
   1252 

[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    455             # instantiate since we don't know how to
    456             raise RuntimeError(msg) from None
--> 457         raise exception
    458 
    459 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 157, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 148, in default_collate
    return torch.as_tensor(batch)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 148, in default_collate
    return torch.as_tensor(batch)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```
Thanks

**Comment by KaiyangZhou** [comment]
The error is caused by `TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.` You can take a look at where the problem occurs.

**Comment by knaticat** [comment]
Yes, I was able to change the dtype in line 148 in the collate.py file. It works fine now. Closing this issue.

**Comment by WHLWJL** [comment]
Hello, I've encountered the same issue. Do you remember the specific line of code you modified? Since the environment is different, the collate.py file might also vary. Could you please provide some guidance? I would greatly appreciate it.
