### ISSUE TITLE
Visualizing ranked images crashes with dukemtmc video.

### ISSUE THREAD

**Issue by MuadDev** [KaiyangZhou/deep-person-reid#52]
Running
```bash
python train_vidreid_xent.py -d dukemtmcvidreid -a hacnn --evaluate --resume saved-models/hacnn_xent_dukemtmcreid.pth.tar --save-dir log/resnet50-xent-dukemtmc --test-batch 2 --gpu-devices 0 --height 160 --width 64 --vis-ranked-res
```
throws
```
Traceback (most recent call last):
  File "train_vidreid_xent.py", line 406, in <module>
    main()
  File "train_vidreid_xent.py", line 223, in main
    topk=20,
  File "/data/rooijenalv/Projects/gitlab-dv/projects/fietsreid/deployment/external/deep-person-reid/torchreid/utils/reidtools.py", line 57, in visualize_ranked_results
    _cp_img_to(qimg_path, qdir, rank=0, prefix='query')
  File "/data/rooijenalv/Projects/gitlab-dv/projects/fietsreid/deployment/external/deep-person-reid/torchreid/utils/reidtools.py", line 50, in _cp_img_to
    dst = osp.join(dst, prefix + '_top' + str(rank).zfill(3) + '_name_' + osp.basename(src))
  File "/opt/conda/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list

```
Possible solution is to change line 44 of file reidtools.py, from
```python
if isinstance(src, tuple):
```
to
```python
if isinstance(src, tuple)  or isinstance(src, list):  # not sure if tuple is needed?
```

**Comment by KaiyangZhou** [comment]
thanks, i have fixed the code

the first item in tracklets is supposed to have been converted to tuple so isinstance(src, tuple) is still required, not sure why this error would happen for dukemtmcvidreid at this moment
