### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by y1b2h3** [KaiyangZhou/deep-person-reid#547]
When I run this command, there is an error problem. How can I solve it？  

python scripts/main.py --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml --transforms random_flip random_erase --root ./data/market1501

Traceback (most recent call last):
  File "main.py", line 191, in <module>
    main()
  File "main.py", line 155, in main
    model = torchreid.models.build_model(
  File "/home/deep-person-reid-master/torchreid/models/__init__.py", line 117, in build_model
    return __model_factory[name](
  File "/home/deep-person-reid-master/torchreid/models/osnet.py", line 533, in osnet_x1_0
    init_pretrained_weights(model, key='osnet_x1_0')
  File "/home/deep-person-reid-master/torchreid/models/osnet.py", line 480, in init_pretrained_weights
    gdown.download(pretrained_urls[key], cached_file, quiet=False)
  File "/usr/local/lib/python3.8/dist-packages/gdown/download.py", line 161, in download
    res = sess.get(url, stream=True, verify=verify)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f79e1a75430>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by jonasMayr314** [comment]
This is an error wit hyour connection. You either have to double check on your connection with the Internet or you have to allow your device to download from google drive (Firewall / ...)
